# Memoria para el daemon de Gradle
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

# Usar librerías AndroidX
android.useAndroidX=true

# Estilo de código Kotlin
kotlin.code.style=official

# R class no transitiva (recomendado)
android.nonTransitiveRClass=true

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
